services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"